### ISSUE TITLE
Struggling to get set up - open api 429 error

### ISSUE THREAD

**Issue by TheMany172** [logancyang/obsidian-copilot#11]
Hello,

Apologies that this may well be a 'me setting it up wrong' thing

But I cannot get the plugin to work

I have downloaded the files and moved them into the directory specified - I also tried using Obsidian BRAT when it didnt work

I have logged into chatGPT online and made an API key and pasted it in the settings for copilot and have it enabled etc

when I open it and enter a chat I get an error popup saying open api error: null pls see console etc

the console for it is:

```
Error in streamSSE: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

getAIResponse @ plugin:copilot:37823
```

the error is quite clear, but I can log in and use chat gpt just fine, i am on a normal free plan and don't really use it much yet, so shouldn't be beyond whatever their free amount is

Is there some setting somewhere I am failing to see/change?

**Comment by logancyang** [comment]
No worries! I just googled this error message and this is the page I was looking at https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details

My guess is that you have not set up the payment in your OpenAI account? The API is not free, but OpenAI gives you a small credit to get started (it was $120 for me since I signed up early, but it expired the next month). Could you check if you have set up the payment correctly in OpenAI, and then test here: https://platform.openai.com/playground?mode=chat

If that works, come back to the plugin and try again. Also, the plugin is currently available in Obsidian Community Plugin, you no longer need to do the manual installation. Let me know if this helps!

**Comment by TheMany172** [comment]
Ah yes, that is it, I have not set up payment - the free amount prior to setting up (at least for me) is $0
So no wonder it wasn't working...

Thanks Logan - will close the issue

![openapi issue](https://github.com/logancyang/obsidian-copilot/assets/110791742/6e165b45-efae-4997-8a2e-ba295ae585ee)

**Comment by logancyang** [comment]
@TheMany172  Glad it helped! This is actually a common issue, I will add a FAQ section in the readme soon to include it. Thanks for reporting!

Also, I'm thinking about adding a completely local and free solution so that there is no need to call OpenAI. Please stay tuned!

**Comment by TheMany172** [comment]
Will do, good luck with it all 🫠
