### ISSUE TITLE
Wrong language used with Copilot and text selection

### ISSUE THREAD

**Issue by oneill4789** [logancyang/obsidian-copilot#130]
First, thank you for creating such a wonderful plugin.

The problem: The wrong language is used and it appears to be random. Sometimes it's Spanish, other times it's German, but it's never English and that's the language of the note.

Steps to reproduce:
1. Select text in note
2. From command menu, choose "Copilot: Make selection longer"
3. Note that the output is not in English

**Comment by logancyang** [comment]
@oneill4789 thanks for reporting. The "make longer" prompt is simply this:

```
user message: Please rewrite the following text to make it twice as long while keeping the meaning as much as possible. Output in the same language as the source, do not output English if it is not English:
```

You can check by turning on the debug mode and opening the dev console. Notice the "do not output English if it is not English" part, so if the model deems the input text not English, it will not output English. Since you mentioned it's quite random, I guess it's gpt3.5 and your note somehow has stuff it considered as Spanish or German. Can you try GPT4 and see if it's reproducible?

If you don't like this prompt and would like it to always output in English, you can create your own custom Copilot prompt too.

**Comment by oneill4789** [comment]
@logancyang thank you for responding so quickly and on a weekend! I wanted to confirm that GPT4 did resolve the issue. I also didn't know I could create a Copilot prompt. I will explore that, too.

Thanks again for the help and making a great plugin. It's very useful.
