### ISSUE TITLE
Feature Request: Be able to use OpenAI fine tuned model

### ISSUE THREAD

**Issue by shuxueshuxue** [logancyang/obsidian-copilot#136]

**Comment by Sokole1** [comment]
Hi @shuxueshuxue it should technically be possible by first setting OpenAI Proxy Base URL to: `https://api.openai.com/v1` and LocalAI model to `ft:gpt-3.5-turbo:my-org:custom_suffix:id`. You can try this for now, but this isn't ideal. It might be good to implement a "Custom Model" command that allows you to specify certain settings like the model, base url, temperature, token limit, etc. Then be able to choose your custom model in the chat drop-down.

<img width="798" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/68660379/f1770f09-46c2-449c-a18d-75138c8d0a02">


Since I don't have any fine-tuned models, below is an example where I set LocalAI model to `gpt-3.5-turbo` instead (notice how I selected LocalAI):
<img width="1057" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/68660379/861abeed-b74c-46f9-afdf-370b9efea3e0">

**Comment by AMGMNPLK** [comment]
Do you have in your roadmap having a local fine tuned model?
