### ISSUE TITLE
Feature request: In QA Active Note mode, do not split entire note if context size of model is big enough. 

### ISSUE THREAD

**Issue by RobKnop** [logancyang/obsidian-copilot#150]
When I use the QA Active Note Mode and the GPT from OpenAI, then the model thinks there are two articles and it hard to ask about your Note as everything is splitter und you won't get response regarding your whole note.

**Comment by logancyang** [comment]
@RobKnop I've been thinking about this as well. Since the current QA mode is RAG and does not support queries containing words like "this article/note", a better experience would be having the ability to reference a note with the title right inside Conversation mode with `[[ ]]` without RAG, purely passes the note to the model with a larger context window. If the note is not super long, the model understands it better.

QA mode (RAG) should be used only for specific queries on longer notes. This way we have the flexibility of both worlds.

**Comment by logancyang** [comment]
Closing as outdated.
