### ISSUE TITLE
[FR] Add customization to the local embedding model

### ISSUE THREAD

**Issue by wwjCMP** [logancyang/obsidian-copilot#381]
Now I need to change the embedding model in ollama to the name preset by this plugin, and I hope to be able to customize the name of the embedding model.

**Comment by leethobbit** [comment]
As an additional comment - has there been any research into adding a local embedding scheme that doesn't even require an LLM? A similar plugin, Smart Connections, offers a variety of embedding options that can be ran right from the plugin.  I think it would be great to ship one or two similar options so that users with LM Studio (or users without the desire to spin up a second model) can just leave the embeddings generation to the plugin.

**Comment by logancyang** [comment]
@leethobbit Thanks for the suggestion. I believe Smart Connections uses transformers.js for that and not Ollama for that to happen. I tried once before but couldn't make transformers.js work in the Obsidian plugin env. Not sure how they made it work, but it's certainly possible given that they've done it already.

**Comment by leethobbit** [comment]
Thanks for the quick response! I'm mostly a Python dev and don't have a strong grasp on either JS or the AI embedding stuff, but I'll take a look at both plugins to see if I can't help in some way.

**Comment by muzhi1991** [comment]
I also need a model that supports chinese embedding, need this feature

**Comment by zhcqiu** [comment]
> I also need a model that supports chinese embedding, need this feature

I hope so! 
Copilot could do something like the smart connections plug which provides Jina v2 (EN & CN)

**Comment by logancyang** [comment]
With custom models, closing this old issue. If anything is not working with custom model, please open separate issues with details.

**Comment by tredondo** [comment]
How exactly can embedding generation be done locally/offline? I don't see any local embedding providers such as Ollama in the Embedding Models settings:

<img width="995" height="875" alt="Image" src="https://github.com/user-attachments/assets/b73d4aba-4f75-4c00-aa20-9cd69d11db66" />
