### ISSUE TITLE
Setting to set default chat mode

### ISSUE THREAD

**Issue by brandones** [logancyang/obsidian-copilot#393]
**Is your feature request related to a problem? Please describe.**

I don't really have a use for "Chat" mode—I use a tab in my browser for that. Every time I open Copilot I have to click to change the setting to "Vault QA"

**Describe the solution you'd like**

A dropdown in settings that lets me set which mode is the default.

**Describe alternatives you've considered**

The plugin could remember which mode was used last, including across Obsidian restarts. This would be a really good solution too. Maybe a better solution, actually, for not cluttering Settings.

**Additional context**

Thanks for the awesome plugin!!!

**Comment by logancyang** [comment]
Have you used User Custom Prompts? Those are powerful features only available in Chat mode, and not possible in your browser. The philosophy of Chat mode is to directly pass the long context to the model, it's particularly useful for long context window models.

But point taken, mode selection could be persisted across sessions. The thing is, perhaps in future iterations there won't be modes at all. There will be a single mode where you indicate Vault QA with a key combo such as `cmd+enter` instead of enter.

**Comment by brandones** [comment]
Oh cool, no I hadn't used that feature. But that kind of thing just isn't part of my workflow at this time—I use AI for research, not content generation, and rarely for editing. My main use case is basically just glorified semantic search through my notes, most of which are highlights from articles. Vault QA does a much better job of this than any other plugin I've tried.
