### ISSUE TITLE
Please Add Other Claude 3 Models

### ISSUE THREAD

**Issue by 1of13** [logancyang/obsidian-copilot#406]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is:
I would like to be able to select from the new Claude3 models (e.g., claude-3-haiku-20240307)

**Describe the solution you'd like**
A clear and concise description of what you want to happen: 
All three new claude3 models are available from the selection menu.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered: 
There are no alternatives.

**Additional context**

**Comment by logancyang** [comment]
At the moment you can provide the Claude model names in the setting directly. 

Are you specifically asking for them to be added to the menu? The number of models is getting big and it's not scalable to add everything to the menu. Claude also doesn't have model alias like OpenAI that points to the latest version of a model, so that's another reason I wouldn't add these to the menu.
