### ISSUE TITLE
How to set up  local Ollama?

### ISSUE THREAD

**Issue by Pathsis** [logancyang/obsidian-copilot#437]
Greetings!

I'm excited to install the awesome Obsidian-Copilot on **Ubuntu**, but I'm not sure how to set up the **local** Ollama.

I've read [Local Copilot Setup Guide](https://github.com/logancyang/obsidian-copilot/blob/master/local_copilot.md) carefully, but, perhaps because I'm too dull, I'm not quite sure what the "Important note about setting context window" part means.

I can currently run **llama3:8b** through Ollama, and I can chat with llama in the terminal. That's as far as I've gotten so far.

So, what command should I run in the terminal next to start Obsidian-Copilot's local Ollama service?

Endless thanks! 😳

**Comment by Pathsis** [comment]
当我在终端运行

```shell
OLLAMA_ORIGINS=app://obsidian.md* ollama serve
```
返回的是

```shell
Error: listen tcp 127.0.0.1:11434: bind: address already in use
```
运行

```shell
lsof -i :11434
```

返回

```shell
COMMAND    PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
obsidian 14624 midtail   24u  IPv4 118196      0t0  TCP localhost:44910->localhost:11434 (ESTABLISHED)
````

**Comment by epchris** [comment]
If you're on MacOS, some methods of installing Ollama end up starting up an instance of ollama that you can find a control for in your toolbar at the top of your screen.  I don't have a ton of experience with MacOS so I don't know how to disable it permanently (maybe someone else can chime in), but if I notice the Ollama icon up there, I right click on it and quit it.  Doing this allows for starting it from the command line with the `OLLAMA_ORIGINS` env var.

Maybe someone else can chime in about how you can permanently set that env var so the one that starts up automatically can see it, but hopefully this helps you get unblocked!

**Comment by epchris** [comment]
Can you share your `ollama.service` file contents?

**Comment by epchris** [comment]
Maybe just to clarify context: If you've set up a systemd service to run ollama and have it enabled, then it's going to be running in the background all the time and you wouldn't be able to (or probably want to) launch a separate instance of ollama via the command line (without manually changing the conflicting port).

So, if you want to always manually run it, you can disable your `ollama.service` so that it doesn't launch in the background.  If you want the service to be always running in the background, then we need to figure out how to set the ENV variable properly in that context.

**Comment by Pathsis** [comment]
@epchris 谢谢你迅速的回应！我使用[这里](https://github.com/logancyang/obsidian-copilot/discussions/419#discussioncomment-9148105)提供的方法，成功解决我在 Ubuntu 上运行 Obsidian-copilot 的问题。

**Comment by epchris** [comment]
> @epchris Thanks for the quick response! I used the method provided [here](https://github.com/logancyang/obsidian-copilot/discussions/419#discussioncomment-9148105) to successfully solve my problem of running Obsidian-copilot on Ubuntu.

Perfect!

**Comment by duracell80** [comment]
This worked for me on Linux with systemd in ollama.service instead of app://

Change
`OLLAMA_ORIGINS="app://obsidian.md*"`

To
`OLLAMA_ORIGINS="*"`

In ollama.service
`$ sudo systemctl edit ollama.service`

Under [Service] add this line then save
`Environment="OLLAMA_ORIGINS=*"`

Then
```
$ sudo systemctl daemon-reload
$ sudo systemctl restart ollama
```

https://medium.com/dcoderai/how-to-handle-cors-settings-in-ollama-a-comprehensive-guide-ee2a5a1beef0
