### ISSUE TITLE
{#tag1, #tag2} placeholder doesn't work in custom prompts.

### ISSUE THREAD

**Issue by hb-man** [logancyang/obsidian-copilot#491]
## The problem
"Create custom prompt" and "Apply ad-hoc custom prompt" offer several dynamic placeholders - for current selection, for specific notes, for a folder of notes and for all the notes tagged with specific tag or sets of tag.
The latter doesn't work at all.

When you try to use the format {#tag1, #tag2}, the Obsidian-Copilot simply responses that "No valid notes found for the provided path '#tag1, #tag2'"

From the error message it looks like a bug in recognition of the placeholder syntax. Since folder path placeholder is `{FolderPath}`, it seems when you use tag placeholder syntax it doesn't recognize it as such and tries to find a folder instead.

## Reproduction steps
1) Open any note, open command palette and select "Obsidian: Apply ad-hoc custom prompt"
2) In the input window for the custom prompt enter `{#tag1}` (replace `#tag1` with any tag that you have notes with)
3) Click Enter, see error message "No valid notes found for the provided path '#tag1'"

## Expected behavior
User expects the chat to receive all the notes with the provided tag to be sent as the context for the chat.

## Screenshots
On the screenshot you can see search panel with the search for the tag #job opened, so I have the notes with such a tag despite the error message of the plugin.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/44e9c160-3367-4887-81f8-82658660b4bd">
<img width="400" alt="image" src="https://github.com/user-attachments/assets/b5c42da5-9ed4-4b25-91f0-2ecf5dd8f7fc">

**Comment by logancyang** [comment]
@hb-man I couldn't reproduce this. What does your note look like?

It could be a misunderstanding. You must have the tag in your note property for it to work, not just anywhere in your note.
<img width="525" alt="SCR-20240810-kmlz" src="https://github.com/user-attachments/assets/359d1707-a755-4af0-93c8-13803a7e2e38">
<img width="383" alt="SCR-20240810-kmod" src="https://github.com/user-attachments/assets/977da103-9de1-48c2-9a53-1511037e7bfc">

If you have the tags inline, they are not supported for now. The reason is that people may have many tags at block level rather than note level. A block level tag should not fetch the entire note as context. Block level tags will be supported next.

**Comment by hb-man** [comment]
You are right, it is indeed a misunderstanding - I didn't even know about properties until your comment. 
They are well hidden, even when pointed out i had to google where how to add them to note.

From the description of the placeholder it's not clear that you mean something other than inline tags, if one isn't aware of properties existence.

Thanks for the clarification.
