### ISSUE TITLE
it's not using my note as context

### ISSUE THREAD

**Issue by Krunsher** [logancyang/obsidian-copilot#51]
First, I clicked on "Use active note as context"
I'm having this issue, it's not using my note as context:

Reading [[My note]]...
Please switch to "QA: Active Note" to ask questions about it.

or

I have Read [[Adam]].
Please switch to "QA: Active Note" to ask questions about it.

![2023-06-01_14-57](https://github.com/logancyang/obsidian-copilot/assets/128519591/1afbeb89-a866-432e-98c7-b16df69807e1)

**Comment by logancyang** [comment]
Have you switched to "QA: Active Note" in the chain selection dropdown?

**Comment by Krunsher** [comment]
I'm looking for the place to do this and I can't find it.

**Comment by logancyang** [comment]
It's the new dropdown menu right next to the button you clicked, says "Conversation" by default, shows "Chain Selection" when you hover over it. Seems this is confusing for some folks. 

I'm considering removing the old button because switching to QA:Active Note is enough to start the QA, the button is not necessary anymore unless you would like to switch to another context. But even switching context is possible without that button because you can always switch back to Conversation and then back to QA to switch context.

**Comment by Krunsher** [comment]
Oh yes, I did! I had thought that all I had to do was click that button. The "Conversation" button went unnoticed, I didn't think it was a drop-down menu.

**Comment by Krunsher** [comment]
About the context, how many words are you limited to? Or is it like the conversation continued?

**Comment by logancyang** [comment]
I'm updating the old button to "Rebuild index for active note" and putting it to the right of the dropdown menu for now. And I renamed the dropdown to "Mode Selection". Will be updated in the next release.

**Comment by logancyang** [comment]
> About the context, how many words are you limited to? Or is it like the conversation continued?

Not sure I understand your question. In QA mode, the context is the note itself, it has unlimited length (in the next step I'm persisting it in a local DB that has a max item size of 4GB, that is still crazy long for plain text). In conversation mode, the conversation context is governed by "Conversation turns in context" parameter in the settings.

**Comment by logancyang** [comment]
> About the context, how many words are you limited to? Or is it like the conversation continued?

Oh if you are asking if there's conversation context in QA mode, like if you asked question A in QA mode, when you ask question B will it remember question A. The answer is no at this time. Every QA question is one-off for now. 

Initially I was implementing a solution that has conversation history in QA mode. But that was blocked by a bug on the LangchainJS side. So I'm using one-off QA for now, but once the bug is fixed, Copilot will remember your conversation even in QA mode. Hopefully very soon!

**Comment by logancyang** [comment]
Closing this one. It is referenced in FAQ.
