### ISSUE TITLE
Can we support Microsoft azure openAI 

### ISSUE THREAD

**Issue by wpzero** [logancyang/obsidian-copilot#68]
At present, the microsoft has released the openAI services on azure. can we support azure openAI?

**Comment by logancyang** [comment]
Will look into this. I personally don't have access to it, may need to test with you before release if you have access.

**Comment by logancyang** [comment]
Just got access to it, will test it out and add it to a new release soon!

**Comment by cl1107** [comment]
1、I selected AZURE GPT-3.5 as the Default Model in my settings. when i open obsidian report this error 
![image](https://github.com/logancyang/obsidian-copilot/assets/21985353/de54fec4-9e12-4d84-974f-0a4e59e0fd62)
2、By default, GPT-3.5 16K is selected in the chat view instead of the Default Model set in the default settings. Even if I change it to another model, it will reset to GPT-3.5 16K when I restart Obsidian.
![image](https://github.com/logancyang/obsidian-copilot/assets/21985353/708e3b6b-5a46-4f4a-88b2-084cb8b8a216)
![image](https://github.com/logancyang/obsidian-copilot/assets/21985353/dd50672a-24e3-4b54-acf6-d90c4564151d)

**Comment by logancyang** [comment]
@cl1107 hmm I can reproduce this, looks like a bug where default model is not respected. Opening a new issue and closing this one.
