### ISSUE TITLE
Indexing on mobile devices isn't working properly

### ISSUE THREAD

**Issue by annaskoulikari** [logancyang/obsidian-copilot#815]
Copilot version: 2.7.2

This plugin is so cool that I also want to use it on the mobile app but I am having an issue. On the mobile app, in the settings, I have not selected the "Disable index loading on mobile" option. However, I still get the "Indexing is disabled on mobile devices" notification. See screenshots below: 

![copilot_mobile_2](https://github.com/user-attachments/assets/66d4225c-b627-4685-833e-fc4cfe4eaa3c)
![copilot_mobile](https://github.com/user-attachments/assets/98e005b8-a0c7-4f3c-9407-dc3b521a6a44)

**Comment by logancyang** [comment]
Hi @annaskoulikari, thanks for reporting. It's a bit harder to debug on mobile because of the lack of dev console. This "Indexing is disabled on mobile devices" is triggered by this code

```
if ((Platform.isMobile && this.settings.disableIndexOnMobile) || !this.oramaDb) {
    new Notice("Indexing is disabled on mobile devices");
    return 0;
}
```

Given that your setting doesn't have it disabled, the reason could be that the orama db is somehow not initialized correctly on your device. 

Questions
1. Is it working on desktop for the same vault?
2. What mobile device and OS version and obsidian version are you on?

If other people also see this error, please share your experience!

**Comment by wtomh** [comment]
Only slightly related (so ignore if its on the wrong path)- but I'm getting the same error on two desktop installs (one on Windows, one on MacOS) when I try to index a vault that is stored on my NAS. It then goes ahead and indexes anyway though...

![image](https://github.com/user-attachments/assets/9d8a374d-00ff-4d35-8abe-5aac482c0284)

**Comment by logancyang** [comment]
I can repro on desktop now. Will put up a fix.

**Comment by logancyang** [comment]
Reopen if this is still not working for you

**Comment by gislf** [comment]
On Mac mini M1 I have the same issue. Indexing does not work even uncheck the box for mobile devices.
