### ISSUE TITLE
Only 3 commands show

### ISSUE THREAD

**Issue by Sean19899999** [logancyang/obsidian-copilot#97]
<img width="584" alt="image" src="https://github.com/logancyang/obsidian-copilot/assets/129134672/27294bea-e9c8-4cac-acb3-9a281b5844a1">

**Comment by logancyang** [comment]
Can you tell me more about how to reproduce this.

https://github.com/logancyang/obsidian-copilot/discussions/95

**Comment by mashean** [comment]
as an FYI...I think I figured out the issue...the issue is not with the plugin but the context in which to use the commands.  Without any selection and invoking the command pallet, looks like you only have these 3 commands.  But when you select text and then invoke Copilot in the CP, you get the full range of commands available...

**Comment by logancyang** [comment]
@mashean That's interesting. However I still can't reproduce, even if I don't select anything I can still see all commands

<img width="1110" alt="Screenshot 2023-07-05 at 10 49 45 AM" src="https://github.com/logancyang/obsidian-copilot/assets/4860545/9472fa0f-328e-4bed-a8af-d045353c0185">

**Comment by mashean** [comment]
I would prefer my instance to work like yours.  If that's the way it's designed to work, I suppose there is a bug or conflict in my Obsidian setup.  Hoping the gremlins will go away with the next release :)

Thanks and do love your plugin!

**Comment by ruben-sg** [comment]
Any news on that? I got only four (the three mentionned plus "Toggle Copilot Chat Window in Note Area")

**Comment by logancyang** [comment]
@ruben-sg could you tell me more about how to reproduce this issue?

**Comment by ruben-sg** [comment]
I can, but it's somehow weird. Yesterday, I only got the four mentionned prompts when looking for them without any selection made. When I made a selection (for example a text in a note) I saw all of them. Today, I can see all the prompt even without a selection. Don't know what's happening tomorrow :)

**Comment by logancyang** [comment]
@ruben-sg @mashean @Sean19899999 
OK I just decyphered it! It's because your editor isn't focused. For example, if you type in the Copilot Chat text box and open the command pallet, you won't see those Copilot commands simply because you are not active in the note editor.

This is the expected behavior, when you have the note edit focused with text selection, those commands should be there. Please let me know if you guys see this problem in other cases.

**Comment by ruben-sg** [comment]
Thanks for getting back to me! Will let you know if I experience other problems!
